server:
  port: 9000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      data-locations:
        - classpath:sql/init.sql
  h2:
    console.enabled: true

security:
  oauth2:
    authorization:
      token-key-access: permitAll()
      check-token-access: permitAll()
      jwt:
        key-store: classpath:smactbus-keystore.jks
        key-password: smactbus
        key-store-password: smactbus
        key-alias: smactbus-keystore
    client:
      client-id: smactbus-api
      client-secret: smactbus-secret
      access-token-validity-seconds: 100
      refresh-token-validity-seconds: 2592000 # 30 days
      authorized-grant-types: password,authorization_code,refresh_token